version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: >
      sh -c "pipenv run python manage.py wait_for_db && 
             pipenv run python manage.py migrate &&
             pipenv run python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=admin
      - DB_USER=postgres
      - DB_PASS=admin@mysecretpassword
      - DB_PORT=5432
    depends_on: 
      - db
  
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "pipenv run python consumer.py"
    depends_on:
      - db

  
  db:
    image: postgres:11-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=admin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin@mysecretpassword
    ports:
      - 5432:5432